image:
  file: .gitpod.Dockerfile
  
tasks:
  - init: |
      go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      export PATH="$PATH:$(go env GOPATH)/bin"
    
gitConfig:
  alias.co: checkout
  alias.ci: commit
  alias.st: status
  alias.oops: commit --amend -C HEAD

vscode:
  extensions:
    - EditorConfig.EditorConfig
